name: nova
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+8

environment:
  sdk: ^3.7.0

dependencies:
  android_intent_plus: ^5.3.0
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  debounce_throttle: ^2.0.0
  device_info_plus: ^10.1.2
  dio: ^5.3.3
  equatable: ^2.0.5
  file_picker: ^8.0.7
  firebase_analytics: ^11.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_remote_config: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.4
  fs_shim: ^2.3.4
  get_it: ^7.6.0
  go_router: ^14.8.0
  http_parser: ^4.0.2
  image:
  image_picker: ^1.0.7
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_overlay: ^0.3.0
  logging: ^1.2.0
  native_dio_adapter: ^1.4.0
  package_info_plus: ^8.0.2
  path: ^1.9.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_otp_text_field: ^1.5.1+1
  pretty_dio_logger: ^1.4.0
  provider: ^6.0.5
  intl_phone_field: ^3.2.0
  retrofit: ^4.4.2
  shared_preferences: ^2.2.0
  synchronized: ^3.3.1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  just_audio: ^0.10.4
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.1
  sign_in_with_apple: ^7.0.1
  glassmorphism_widgets: ^0.2.2

dev_dependencies:
  build_runner: ^2.4.11
  copy_with_extension_gen: ^5.0.4
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  retrofit_generator: ">=9.0.0 <10.0.0"
  go_router_builder: 2.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: normal

flutter_native_splash:
  color: "#ff341401"
  image: assets/images/nova_logo.png
  android: true
  ios: true